package api

const dashboardHTML = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GoalForge</title><style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#151d33;--line:#2b385b;--text:#e7ecf7;--muted:#9daaca;--ok:#4ade80;--wait:#fbbf24;--bad:#fb7185}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#17213d,var(--bg) 48%);color:var(--text);font:15px/1.5 system-ui,sans-serif}
main{max-width:1120px;margin:auto;padding:40px 22px}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:26px}h1{font-size:30px;margin:0}.sub{color:var(--muted)}
#projects{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}.card{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:16px;padding:20px;box-shadow:0 18px 50px #0004}.row{display:flex;justify-content:space-between;gap:12px}.state{font-size:12px;padding:4px 9px;border:1px solid var(--line);border-radius:999px}.bar{height:8px;background:#26314e;border-radius:10px;overflow:hidden;margin:16px 0}.bar span{display:block;height:100%;background:linear-gradient(90deg,#38bdf8,#4ade80)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.metric{background:#0d1427;border-radius:10px;padding:9px}.metric b{display:block;font-size:17px}.metric small{color:var(--muted)}button{background:#263556;color:var(--text);border:1px solid #40517a;border-radius:9px;padding:7px 11px;cursor:pointer}.error{color:var(--bad)}
</style></head><body><main><header><div><h1>GoalForge</h1><div class="sub">목표 중심 AI 개발 오케스트레이터</div></div><button onclick="load()">새로고침</button></header><div id="status" class="sub">불러오는 중…</div><section id="projects"></section></main>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const status=document.querySelector('#status'),root=document.querySelector('#projects');status.textContent='불러오는 중…';root.innerHTML='';try{let token=sessionStorage.getItem('goalforgeToken')||'',r=await fetch('/api/v1/projects',{headers:token?{Authorization:'Bearer '+token}:{}});if(r.status===401){token=prompt('GoalForge API token')||'';if(token)sessionStorage.setItem('goalforgeToken',token);r=await fetch('/api/v1/projects',{headers:{Authorization:'Bearer '+token}})}if(!r.ok)throw new Error((await r.json()).error);const data=await r.json();status.className='sub';status.textContent=data.projects.length+'개 프로젝트';for(const x of data.projects){const p=x.project,m=x.metrics,g=x.goal||{};const el=document.createElement('article');el.className='card';el.innerHTML='<div class="row"><div><strong>'+esc(p.Name)+'</strong><div class="sub">'+esc(p.Provider)+' · '+esc(p.Model||'default')+'</div></div><span class="state">'+esc(p.State)+'</span></div><h3>'+esc(g.Title||'목표 미등록')+'</h3><div class="bar"><span style="width:'+Math.max(0,Math.min(100,x.progress_percent))+'%"></span></div><div class="row sub"><span>진행률</span><span>'+x.progress_percent.toFixed(1)+'%</span></div><div class="metrics"><div class="metric"><b>'+m.RunsTotal+'</b><small>실행</small></div><div class="metric"><b>'+m.WorkDone+'</b><small>완료 작업</small></div><div class="metric"><b>'+m.CostUSD.toFixed(2)+'</b><small>USD</small></div></div>';root.appendChild(el)}}catch(e){status.className='error';status.textContent=e.message}}
load();
</script></body></html>`
