package standards

// GoReactOfflineService is the common development pack for a Go server with a
// React front end intended to run on an isolated network.
//
// It is data rather than a prompt because a prompt cannot be checked. Every
// criterion here carries what would settle it and what evidence that takes, so
// the catalogue can be compared against a repository instead of quoted at one.
//
// Criteria that only apply to some projects carry an applies_when: a project
// with no AI is not failing the streaming criterion, and reporting it as a gap
// would bury the gaps it does have.
func GoReactOfflineService() Pack {
	return Pack{
		ID:      "go-react-offline-service",
		Version: "0.1",
		Title:   "Go · React 폐쇄망 서비스 공통 개발팩",
		Source:  "docs/STANDARDS.md",
		Standards: []Standard{
			{ID: "CORE-001", Revision: 1, Title: "서버 Go · 웹 React 및 이름 일관성", Category: "architecture",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "static", Assertion: "서버는 Go, 웹은 React 로 구성된다"}, {Type: "static", Assertion: "서비스명·저장소·로고·제품명이 화면·문서·이미지에서 일치한다"}},
				EvidenceRequired: []string{"commit_sha", "build_log"},
				ChangeScopeHint:  []string{"**"}},
			{ID: "CFG-001", Revision: 1, Title: "런타임 환경변수 네 종류 제한", Category: "configuration",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "integration", Assertion: "POSTGRES_DSN·BOOTSTRAP_ADMIN·BOOTSTRAP_ADMIN_PASSWORD·ENCRYPTION_KEY 만으로 최초 기동한다"}, {Type: "static", Assertion: "그 밖의 필수 환경변수가 없다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/config/**", "cmd/**"}},
			{ID: "CFG-002", Revision: 1, Title: "운영 설정은 관리자 화면에서 관리하고 Postgres 에 보존", Category: "configuration",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "설정을 저장한 뒤 재기동해도 유지된다"}, {Type: "browser_journey", Assertion: "즉시 적용과 재시작 필요를 구분해 표시한다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"internal/admin/**", "web/src/**"}},
			{ID: "CFG-003", Revision: 1, Title: "초기 관리자 생성은 멱등적", Category: "configuration",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "integration", Assertion: "다중 인스턴스 동시 최초 기동에도 관리자가 중복 생성되지 않는다"}, {Type: "integration", Assertion: "재기동이 바뀐 비밀번호·권한을 초기화하지 않는다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/bootstrap/**"}},
			{ID: "CFG-004", Revision: 1, Title: "비밀 설정의 마스킹·권한·변경 이력", Category: "security",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "security", Assertion: "API 응답·로그·감사 diff 에 비밀 평문이 남지 않는다"}},
				EvidenceRequired: []string{"commit_sha", "security_test_result"},
				ChangeScopeHint:  []string{"internal/admin/**", "internal/audit/**"}},
			{ID: "NET-001", Revision: 1, Title: "폐쇄망 기본 모드", Category: "network",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"network": "offline"},
				Checks:           []Check{{Type: "integration", Assertion: "인터넷 송신을 차단한 환경에서 핵심 여정이 통과한다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"**"}},
			{ID: "NET-002", Revision: 1, Title: "프런트엔드 자산 로컬 제공", Category: "network",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"network": "offline"},
				Checks:           []Check{{Type: "browser_journey", Assertion: "브라우저 요청에 미허용 외부 도메인이 없다"}, {Type: "static", Assertion: "런타임 CDN·외부 텔레메트리 참조가 없다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"web/**"}},
			{ID: "AUTH-001", Revision: 1, Title: "로컬 로그인과 내부 OIDC", Category: "auth",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "로컬 로그인과 내부 OIDC 로 각각 로그인된다"}, {Type: "integration", Assertion: "제공자 장애 시 권한 있는 로컬 복구 경로를 쓸 수 있다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"internal/auth/**"}},
			{ID: "AUTH-002", Revision: 1, Title: "외부 소셜 로그인 어댑터", Category: "auth",
				Severity: SeverityRecommended, AppliesWhen: map[string]string{"social_login": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "제공자별 연결 시험이 통과한 뒤에만 활성화된다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/auth/**"}},
			{ID: "AUTH-003", Revision: 1, Title: "OIDC 발견 문서와 OAuth2 어댑터 구분", Category: "auth",
				Severity: SeverityRecommended, AppliesWhen: map[string]string{"social_login": "true"},
				Checks:           []Check{{Type: "static", Assertion: "issuer·client·redirect URI·scope 를 검사한다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/auth/**"}},
			{ID: "AUTH-004", Revision: 1, Title: "인증 연결 마법사", Category: "auth",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "제공자 선택·최소 설정·콜백 복사·연결 시험·활성화를 거친다"}, {Type: "security", Assertion: "인증서 검증을 우회하지 않고 사내 CA 를 지원한다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"web/src/**", "internal/auth/**"}},
			{ID: "AUTH-005", Revision: 1, Title: "외부 계정은 issuer 와 subject 로 식별", Category: "auth",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"social_login": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "같은 이메일만으로 다른 계정을 자동 병합하지 않는다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/auth/**"}},
			{ID: "UX-001", Revision: 1, Title: "기본 언어 한국어", Category: "usability",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "주요 화면의 메뉴·버튼·검증 오류·빈 상태에 누락 번역이 없다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"web/src/**"}},
			{ID: "UX-002", Revision: 1, Title: "관리자 설정과 개인 설정의 분리", Category: "usability",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "일반 사용자에게 관리자 기능이 노출되지 않는다"}, {Type: "integration", Assertion: "서버에서도 관리자 경로 접근을 거부한다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"web/src/**", "internal/http/**"}},
			{ID: "UX-003", Revision: 1, Title: "가독성 기준", Category: "usability",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "확대 200%·모바일 360px·키보드만으로 주요 조작이 가능하다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result", "screenshot"},
				ChangeScopeHint:  []string{"web/src/**"}},
			{ID: "UX-004", Revision: 1, Title: "새로고침과 직접 경로 접근 유지", Category: "usability",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"frontend": "react"},
				Checks:           []Check{{Type: "browser_journey", Assertion: "중첩 경로 직접 접근 시 같은 화면을 표시한다"}, {Type: "browser_journey", Assertion: "필터를 적용한 뒤 새로고침해도 필터가 유지된다"}, {Type: "browser_journey", Assertion: "로그인 후 원래 경로로 안전하게 복귀한다"}},
				EvidenceRequired: []string{"commit_sha", "route", "browser_test_result", "screenshot"},
				ChangeScopeHint:  []string{"web/src/routes/**", "internal/http/**"}},
			{ID: "UX-005", Revision: 1, Title: "메뉴 스크롤바", Category: "usability",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "긴 메뉴를 키보드로 스크롤할 수 있고 스크롤바가 식별된다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"web/src/**"}},
			{ID: "UX-006", Revision: 1, Title: "서비스 버전 표시", Category: "usability",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "로그인 화면과 프로필 메뉴의 버전이 이미지 태그·릴리즈와 일치한다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"web/src/**"}},
			{ID: "UX-007", Revision: 1, Title: "로고·아이콘·파비콘 변형", Category: "usability",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "탭·메뉴·로그인·홍보 페이지에서 밝은·어두운 배경 변형이 확인된다"}},
				EvidenceRequired: []string{"commit_sha", "screenshot"},
				ChangeScopeHint:  []string{"web/public/**", "docs/**"}},
			{ID: "AI-001", Revision: 1, Title: "AI 호출 스트리밍과 취소", Category: "ai",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"ai": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "중단 시 서버 작업 취소가 전파된다"}, {Type: "integration", Assertion: "부분 응답과 완료 응답을 구분하고 중복 실행 없이 재시도한다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/ai/**"}},
			{ID: "AI-002", Revision: 1, Title: "AI 제공자 설정", Category: "ai",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"ai": "true"},
				Checks:           []Check{{Type: "browser_journey", Assertion: "endpoint·model·credential·능력·제한을 관리자 화면에서 설정하고 연결을 시험한다"}, {Type: "static", Assertion: "비지원 기능을 지원한다고 표시하지 않는다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"internal/ai/**", "web/src/**"}},
			{ID: "AI-003", Revision: 1, Title: "문맥 한도와 출력 한도 분리", Category: "ai",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"ai": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "입력·대화·도구·예약 출력의 합이 실제 한도를 넘으면 축약하거나 명확히 실패한다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/ai/**"}},
			{ID: "KEY-001", Revision: 1, Title: "개인 API 키 수명주기", Category: "security",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"api_keys": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "발급·만료·폐기·회전·권한 변경이 동작하고 원문은 발급 시 1회만 표시된다"}, {Type: "integration", Assertion: "폐기와 권한 축소가 캐시에도 신속히 반영된다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/auth/**"}},
			{ID: "KEY-002", Revision: 1, Title: "키 목적별 저장 방식", Category: "security",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"api_keys": "true"},
				Checks:           []Check{{Type: "security", Assertion: "자체 API 키는 해시로, 제공자 키는 암호화로 저장된다"}, {Type: "security", Assertion: "로그·문서·스크린샷에 키가 남지 않는다"}},
				EvidenceRequired: []string{"commit_sha", "security_test_result"},
				ChangeScopeHint:  []string{"internal/auth/**", "internal/crypto/**"}},
			{ID: "KEY-003", Revision: 1, Title: "루트 보호 키와 데이터 키 회전 구분", Category: "security",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "integration", Assertion: "데이터 키 회전·백업 복구·루트 키 교체 절차가 동작한다"}, {Type: "security", Assertion: "루트 키를 관리자 화면에 평문 노출하지 않는다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/crypto/**"}},
			{ID: "INT-001", Revision: 1, Title: "공통 커넥터 계약", Category: "integration",
				Severity: SeverityRecommended, AppliesWhen: map[string]string{"connectors": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "인증·연결 검사·스키마·페이지 처리·속도 제한·타임아웃·체크포인트가 공통 인터페이스를 따른다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/connector/**"}},
			{ID: "INT-002", Revision: 1, Title: "DB 연결 기본 읽기 전용", Category: "integration",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"connectors": "true"},
				Checks:           []Check{{Type: "security", Assertion: "접속 권한과 실제 쿼리 권한이 일치한다"}},
				EvidenceRequired: []string{"commit_sha", "security_test_result"},
				ChangeScopeHint:  []string{"internal/connector/**"}},
			{ID: "INT-003", Revision: 1, Title: "멱등성과 실패 재처리", Category: "integration",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"connectors": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "동일 이벤트를 다시 받아도 중복 부작용이 없다"}, {Type: "integration", Assertion: "실패와 미확정 결과를 구분한다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/connector/**"}},
			{ID: "API-001", Revision: 1, Title: "서비스 API 와 MCP 도구", Category: "architecture",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "integration", Assertion: "UI·API·MCP 가 같은 권한과 정책을 쓴다"}, {Type: "security", Assertion: "다른 사용자의 리소스 접근이 차단된다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/http/**", "internal/mcp/**"}},
			{ID: "WF-001", Revision: 1, Title: "업무 승인은 설정된 경우에만 활성화", Category: "workflow",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"approval_workflow": "true"},
				Checks:           []Check{{Type: "browser_journey", Assertion: "프로세스 미설정 시 승인 메뉴와 대기 상태가 생기지 않는다"}, {Type: "integration", Assertion: "실행 중 프로세스는 적용 당시 버전에 고정된다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"internal/workflow/**"}},
			{ID: "WF-002", Revision: 1, Title: "프로세스 비활성화 시 진행 건 처리", Category: "workflow",
				Severity: SeverityRequired, AppliesWhen: map[string]string{"approval_workflow": "true"},
				Checks:           []Check{{Type: "integration", Assertion: "자동 통과나 유실 없이 기존 버전으로 완료되거나 정해진 전환 정책이 적용된다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{"internal/workflow/**"}},
			{ID: "QA-001", Revision: 1, Title: "핵심 여정과 도달 가능한 페이지 검증", Category: "quality",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "역할별 주요 여정에서 미처리 오류·의도치 않은 콘솔 오류·깨진 주요 버튼이 없다"}},
				EvidenceRequired: []string{"commit_sha", "route", "browser_test_result"},
				ChangeScopeHint:  []string{"web/**", "internal/http/**"}},
			{ID: "QA-002", Revision: 1, Title: "빈 데이터·로딩·실패·권한 없음·모바일 상태", Category: "quality",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "각 상태가 테스트 매니페스트에 실행 또는 제외 근거와 함께 기록된다"}},
				EvidenceRequired: []string{"commit_sha", "browser_test_result"},
				ChangeScopeHint:  []string{"web/**"}},
			{ID: "REL-001", Revision: 1, Title: "React 자산을 서비스 이미지에 포함", Category: "release",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "build", Assertion: "실행 시 Node 설치나 프런트엔드 빌드 없이 기동한다"}},
				EvidenceRequired: []string{"commit_sha", "build_log"},
				ChangeScopeHint:  []string{"Dockerfile", "**"}},
			{ID: "REL-002", Revision: 1, Title: "이미지 태그와 자산 이름 규칙", Category: "release",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "static", Assertion: "이미지는 서비스명:v버전, 자산은 서비스명-v버전.tar.gz 이다"}, {Type: "build", Assertion: "docker save 결과를 gzip 으로 압축한다"}},
				EvidenceRequired: []string{"commit_sha", "build_log"},
				ChangeScopeHint:  []string{".github/**", "Makefile"}},
			{ID: "REL-003", Revision: 1, Title: "릴리즈 자산은 서비스 이미지 tar.gz 만", Category: "release",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "static", Assertion: "DB·개발 도구 이미지를 섞지 않는다"}, {Type: "static", Assertion: "체크섬과 설명이 릴리즈 본문에 있다"}},
				EvidenceRequired: []string{"commit_sha", "release_asset"},
				ChangeScopeHint:  []string{".github/**"}},
			{ID: "REL-004", Revision: 1, Title: "깨끗한 대상에서 로드·기동·업그레이드 검증", Category: "release",
				Severity: SeverityRequired, AppliesWhen: nil,
				Checks:           []Check{{Type: "integration", Assertion: "외부 pull 없이 이미지를 로드해 네 환경변수로 기동한다"}, {Type: "integration", Assertion: "DB 마이그레이션 호환성이 확인된다"}},
				EvidenceRequired: []string{"commit_sha", "integration_test_result"},
				ChangeScopeHint:  []string{".github/**"}},
			{ID: "DOC-001", Revision: 1, Title: "GitHub Pages 홍보 페이지", Category: "documentation",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "제품 설명·사용 사례·설치·FAQ·버전·가이드 링크가 실제 동작과 일치한다"}},
				EvidenceRequired: []string{"commit_sha", "route", "browser_test_result"},
				ChangeScopeHint:  []string{"docs/**"}},
			{ID: "DOC-002", Revision: 1, Title: "SEO·AEO 기본 구조", Category: "documentation",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "static", Assertion: "고유 title·description·canonical, sitemap·robots, 사실과 일치하는 구조화 데이터가 있다"}},
				EvidenceRequired: []string{"commit_sha", "route"},
				ChangeScopeHint:  []string{"docs/**"}},
			{ID: "DOC-003", Revision: 1, Title: "사용자·관리자 가이드 MD·HTML·PDF", Category: "documentation",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "static", Assertion: "동일 원본에서 생성되고 링크·한글 폰트·목차·페이지 분할이 검증된다"}},
				EvidenceRequired: []string{"commit_sha", "build_log"},
				ChangeScopeHint:  []string{"docs/**"}},
			{ID: "DOC-004", Revision: 1, Title: "페이지 캡처 자동 생성", Category: "documentation",
				Severity: SeverityRecommended, AppliesWhen: nil,
				Checks:           []Check{{Type: "browser_journey", Assertion: "라우트·역할·대표 상태 매니페스트에 따라 캡처가 생성된다"}, {Type: "static", Assertion: "캡처의 빌드 버전·커밋·경로가 기록되고 민감정보가 없다"}},
				EvidenceRequired: []string{"commit_sha", "screenshot"},
				ChangeScopeHint:  []string{"docs/**"}},
		},
	}
}
